version: '3.8'
services:
  db:
    container_name: epic-timer-db
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASS
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASS
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
